menu:
  首页: /
  归档: /archives
  # Lab: http://lab.bubkoo.com/
  # 关于: /about
  # 简历: /resume
  Github: https://github.com/bubkoo
  # RSS: /atom.xml

widgets:
  # - category
  - search
  - tagcloud
  - recent_posts
  # - archive
  # - recent_comments
  # - recent_visitors

excerpt_link: 全文
recent_posts_count: 10

blogrolls:
  - Heroic Yang's Blog: http://heroicyang.com/

duoshuo: bubkoo

# 压缩 CSS 选项
compress: true

fancybox: true

baidu_tongji: true

google_analytics:
rss: